name: Blog Post
on: 
    push:
    schedule:
        - cron: '30 * * * *'
    workflow_dispatch:
    
jobs: 
    update-readme-with-blog: 
        name: latest posts from Blog
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v2
            - uses: gautamkrishnar/blog-post-workflow@master
              with: 
                comment_tag_name: "BLOG-POST-LIST"
                max_post_count: "4"
                feed_list: "https://medium.com/feed/@divjot121"
